# Generated by Django 5.0.2 on 2024-10-27 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('slogan', models.CharField(max_length=100, verbose_name='слоган')),
                ('contacts', models.CharField(max_length=255, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'клуб',
                'verbose_name_plural': 'клубы',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата начала')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_run', to=settings.AUTH_USER_MODEL, verbose_name='бегун')),
            ],
        ),
    ]
