# Generated by Django 5.0.2 on 2024-10-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'забег', 'verbose_name_plural': 'забеги'},
        ),
    ]
