# Generated by Django 5.0.2 on 2024-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'init'), (2, 'in_progress'), (3, 'finished')], default=1, verbose_name='статус забега'),
        ),
    ]
