# Generated by Django 5.0.2 on 2024-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('init', 'init'), ('in_progress', 'in_progress'), ('finished', 'finished')], default=1, verbose_name='статус забега'),
        ),
    ]
