# Generated by Django 5.0.2 on 2024-10-30 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время позиции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(default=0, verbose_name='время забега в секундах'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=0, verbose_name='пройденная дистанция в км'),
        ),
    ]
