# Generated by Django 5.0.2 on 2024-10-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='init', max_length=20, verbose_name='статус забега'),
        ),
    ]
