# Generated by Django 5.0.7 on 2024-11-02 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position_distance_position_speed_run_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='бегун')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'подписка на тренера',
                'verbose_name_plural': 'подписки на тренера',
            },
        ),
    ]
