# Generated by Django 5.0.7 on 2024-11-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_subscribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='название')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_challenge', to=settings.AUTH_USER_MODEL, verbose_name='бегун')),
            ],
            options={
                'verbose_name': 'челлендж',
                'verbose_name_plural': 'челленджи',
            },
        ),
    ]
