# Generated by Django 5.0.2 on 2024-11-30 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='долгота')),
                ('picture', models.URLField()),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'коллекционный предмет',
                'verbose_name_plural': 'коллекционные предметы',
            },
        ),
    ]
