# Generated by Django 5.0.2 on 2025-01-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_devtestmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devtestmodel',
            options={'verbose_name': 'dev test model', 'verbose_name_plural': 'dev test models'},
        ),
    ]
