# Generated by Django 5.0.2 on 2024-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_unitlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitlocation',
            name='uid',
            field=models.CharField(default='poi', max_length=8),
            preserve_default=False,
        ),
    ]
