# Generated by Django 5.0.2 on 2024-12-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_unitathlete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitathlete',
            options={'verbose_name': 'награда бегуна', 'verbose_name_plural': 'награды бегуна'},
        ),
    ]
