# Generated by Django 5.0.2 on 2024-12-10 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_unitathlete_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitAthlete',
            new_name='UnitAthleteRelation',
        ),
    ]
