# Generated by Django 5.0.2 on 2024-12-12 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_rename_unitathlete_unitathleterelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='уровень')),
                ('goals', models.CharField(blank=True, max_length=255, null=True, verbose_name='цели')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='атлет')),
            ],
            options={
                'verbose_name': 'информация атлета',
                'verbose_name_plural': 'информация атлетов',
            },
        ),
    ]
