# Generated by Django 5.0.2 on 2024-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0019_coachrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachrate',
            old_name='rate',
            new_name='rating',
        ),
    ]
