# Generated by Django 5.0.2 on 2024-12-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0020_rename_rate_coachrate_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachrate',
            name='athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL, verbose_name='бегун'),
        ),
        migrations.AlterField(
            model_name='coachrate',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL, verbose_name='тренер'),
        ),
    ]
