# Generated by Django 5.0.2 on 2025-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_alter_coachrate_athlete_alter_coachrate_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'test model',
                'verbose_name_plural': 'test models',
            },
        ),
    ]
