# Generated by Django 5.0.2 on 2025-01-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_alter_devtestmodel_options'),
        ('app_run', '0022_testmodel'),
    ]

    operations = [
    ]
